// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(TeaRoundPickerContext))]
    [Migration("20210414185344_DrinkRun")]
    partial class DrinkRun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Persistence.DBModels.DrinkOrderDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalSpecification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DrinkOrder");
                });

            modelBuilder.Entity("Persistence.DBModels.DrinkRunDbModel", b =>
                {
                    b.Property<Guid>("DrinkMakerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("DrinkMakerId");

                    b.ToTable("DrinkRun");
                });

            modelBuilder.Entity("Persistence.DBModels.UserDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Persistence.DBModels.DrinkOrderDbModel", b =>
                {
                    b.HasOne("Persistence.DBModels.UserDbModel", "User")
                        .WithMany("DrinkOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.DBModels.DrinkRunDbModel", b =>
                {
                    b.HasOne("Persistence.DBModels.UserDbModel", "DrinkMaker")
                        .WithOne()
                        .HasForeignKey("Persistence.DBModels.DrinkRunDbModel", "DrinkMakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrinkMaker");
                });

            modelBuilder.Entity("Persistence.DBModels.UserDbModel", b =>
                {
                    b.Navigation("DrinkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
