trigger:
  - main

stages:
    - stage: Build
      displayName: Build & Test
      jobs:
          - job: buildAndTest
            pool: "Default"
            steps:
                - task: UseDotNet@2
                  inputs:
                    version: '5.0.x'
                    
                - task: DotNetCoreCLI@2
                  inputs:
                    command: 'restore'
                    projects: '**/**/*.csproj'
                    feedsToUse: 'select'
                
                - task: DotNetCoreCLI@2
                  displayName: Unit Tests
                  inputs:
                    command: 'test'
                    projects: '**/test/*.UnitTests/*.csproj'
                    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
                    testRunTitle: 'Unit Tests'

                - task: DotNetCoreCLI@2
                  displayName: Integration Tests
                  inputs:
                    command: 'test'
                    projects: '**/test/*.IntegrationTests/*.csproj'
                    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
                    testRunTitle: 'Integration Tests'
                
                - task: DotNetCoreCLI@2
                  inputs:
                    command: custom
                    custom: tool
                    arguments: install --tool-path . dotnet-reportgenerator-globaltool --ignore-failed-sources
                  displayName: Get ReportGenerator tool

                - script: reportgenerator -reports:$(Build.SourcesDirectory)\test\**\coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)\coverlet\reports -reporttypes:"Cobertura"
                  displayName: Generate Coverage Report

                - task: PublishCodeCoverageResults@1
                  displayName: 'Publish code coverage report'
                  inputs:
                    codeCoverageTool: 'Cobertura'
                    summaryFileLocation: '$(Build.SourcesDirectory)\coverlet\reports\Cobertura.xml'
                    
                - task: BuildQualityChecks@8
                  inputs:
                    checkCoverage: true
                    coverageFailOption: "fixed"
                    coverageType: "branches"
                    coverageThreshold: "80"
                    baseBranchRef: "refs/heads/main"
